replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  type: NodePort

admin:
  enabled: true
  type: ClusterIP
  enable_admin_ui: false

etcd:
  enabled: true
  replicaCount: 1
  preUpgradeJob:  
    enabled: false

externalEtcd:
  host:
    - http://case-platform-apisix-etcd.apisix.svc.cluster.local:2379
  user: ""
  
ingress-controller:
  enabled: true
  webhook:
    enabled: false