apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-frontend"
spec:
  ingressClassName: apisix
  rules:
    - http:
        paths:
          - path: {{ .Values.frontend.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-frontend"
                port:
                  number: 80