apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-frontend"
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-frontend"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-frontend"
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5